import "./globals.css";
import type { Metadata } from "next";
import { NavBar } from "./components/navbar";

export const metadata: Metadata = {
  title: "krisette odegard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-background text-onBackground">
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
