import './globals.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'

  const myFont = localFont({
    src: '/Metropolis-Regular.otf',
    weight: '400',
  })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={myFont.className}>{children}</body>
    </html>
  )
}
